### PR TITLE
Annotated property

### PR DESCRIPTION
**Pull request by mauglee**
Annotated property for EasyImage class.
Changed PHPDoc for detectPath() as it is expecting string as parameter.

### CODE REVIEW

**Comment by AxelPAL** [comment]
Why did you remove composer.json?
Also, you should squish your commits into one before merge.

**Comment by mauglee** [comment]
Sorry, I'm not so advanced in git.
`composer.json` should be here intact (I have changed it in my master branch, but here I'm requesting from development).
I tried to squash commits – is it OK now?

**Comment by AxelPAL** [comment]
EasyImage doesn't have property **$image**. It has property **$_image** and it's documented yet.

**Comment by mauglee** [comment]
It is „virtual“ property returned by `getImage()` magic method. So, you can use `$easyimage->image` and IDE autocomplete works fine. It's a small improvement.

**Comment by AxelPAL** [comment]
I know that, 'cause the class extends yii's Component.
But $image in this case can be only **Image** object, not string. Check **setImage()** method.

**Comment by mauglee** [comment]
Yes, you are right. Now fixed that and commited. But I'm a little bit lost what to do next :) I mean here in github...

**Comment by mauglee** [comment]
I'm going forward and already have some improvements regarding retina stuff.
But I am working on my fork https://github.com/mauglee/yii2-easyimage
In a case you want this too, what is mechanism for you to get this into your code? Creating new branch, adding my repo as remote and fetching my changes?

**Pull request merged**
